require_relative 'exercise1'
require_relative 'exercise2'
require_relative 'exercise3'
require_relative 'exercise4'
require_relative 'exercise5'
require_relative 'exercise6'
require_relative 'exercise7'
