AllCops:
  EnabledByDefault: true # disable should be explicit
  Exclude:
    - '.git/**/*'
  CacheRootDirectory: tmp


Bundler/GemVersion:
  Enabled: false

Bundler/GemComment:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end
  IndentOneStep: true

Layout/ClassStructure:
  ExpectedOrder:
    - module_inclusion
    - constants
    - association
    - public_attribute_macros
    - public_delegate
    - macros
    - public_class_methods
    - initializer
    - public_methods
    - protected_attribute_macros
    - protected_methods
    - private_attribute_macros
    - private_delegate
    - private_methods

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementLineBreak:
  Enabled: false

Layout/FirstHashElementLineBreak:
  Enabled: false

Layout/FirstMethodArgumentLineBreak:
  Enabled: false

Layout/HeredocArgumentClosingParenthesis:
  Enabled: false

Layout/MultilineArrayLineBreaks:
  Enabled: false

Layout/MultilineAssignmentLayout:
  Enabled: false

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/RedundantLineBreak:
  Enabled: false

Layout/SingleLineBlockChain:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

Lint/HeredocMethodCallPosition:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/NumberConversion:
  Enabled: false

Metrics/AbcSize:
  Max: 55
  Exclude:
    - 'app/lib/pain/**/*'
    - 'spec/**/*'

Metrics/BlockLength:
  Max: 80
  Exclude:
    - 'app/lib/pain/**/*'
    - 'config/**/*'
    - 'lib/tasks/**/*'
    - 'spec/**/*'

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Max: 229

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'app/lib/pain/**/*'
    - 'lib/tasks/**/*'
    - 'scripts/**/*'
  CountAsOne:
    - array
    - hash
    - heredoc

Metrics/ModuleLength:
  Max: 183

Metrics/ParameterLists:
  Max: 6

Metrics/PerceivedComplexity:
  Max: 15

Naming/AccessorMethodName:
  Enabled: false

Naming/BlockForwarding:
  EnforcedStyle: explicit

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/InclusiveLanguage:
  Enabled: false

# Something like duplicate(x,y) should be ok.
# Use common sense.
Naming/MethodParameterName:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

# Performance/ArraySemiInfiniteRangeSlice:
#   Enabled: false

# Performance/ChainArrayAllocation:
#   Enabled: false

# Performance/OpenStruct:
#   Enabled: false

# Performance/CollectionLiteralInLoop:
#   Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/AutoResourceCleanup:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/ConstantVisibility:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FetchEnvVar:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Style/IfUnlessModifier:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: false

Style/InlineComment:
  Enabled: false

Style/IpAddresses:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/**/*'
    - 'spec/factories.rb'

Style/MultilineBlockChain:
  Enabled: false

Style/NumberedParametersLimit:
  Max: 3

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/OptionHash:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/RescueStandardError:
  Enabled: false

Style/ReturnNil:
  Enabled: false

Style/Send:
  Enabled: false

Style/StringHashKeys:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TopLevelMethodDefinition:
  Include:
    - 'app/**/*'

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/UnlessLogicalOperators:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/AsciiComments:
  AllowedChars:
    - '▯'

Style/OptionalBooleanParameter:
  Exclude:
    - 'app/jobs/**/*'
